version: '3.8'
services:
  # --------------------------------------
  db:
    image: mysql:latest
    hostname: db
    environment:
      MYSQL_DATABASE: english_words_development
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  # --------------------------------------
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    environment:
      BUNDLE_HOME: '/app'
      DATABASE_NAME: 'english_words_development'
      DATABASE_USERNAME: 'root'
      DATABASE_HOSTNAME: 'db'
      DATABASE_PASSWORD: 'pass'
      RAILS_PORT: 53000
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - '53000:3000'

volumes:
  db-data:
